import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isArabic: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.about": "About",
    "nav.faq": "FAQ",
    "nav.manuals": "Manuals",
    "nav.login": "LOGIN",
    "nav.language": "العربية",
    "index.welcome": "Welcome to",
    "index.vendorHub": "ECA Vendor Hub",
    "index.subtitle": "Please Login to access the requests",
    "index.email": "Email Address",
    "index.password": "Password",
    "index.loginBtn": "LOGIN",
    "index.register": "REGISTER NOW",
    "index.registerText": "Don't have an account?",
    "footer.copyright": "Copyright © {year} ECA. All Rights Reserved.",
    "footer.terms": "Terms of Use",
    "footer.privacy": "Privacy Policy",
    "about.title": "About ECA Vendor Hub",
    "about.mission": "Our Mission",
    "about.missionText": "The ECA Vendor Hub is a comprehensive portal designed to streamline vendor engagement with ECA activities. Our mission is to provide a centralized, user-friendly platform where vendors can efficiently access engagements, manage contracts, and collaborate on projects with the ECA.",
    "about.whatWeDo": "What We Do",
    "about.whatWeDoText": "The ECA Vendor Hub serves as the official public portal for vendor engagement with ECA activities. Through this platform, vendors can:",
    "about.features": "Key Features",
    "about.engagement": "Engagement Management",
    "about.engagementDesc": "Track and manage all your active engagements with real-time updates and status monitoring.",
    "about.contract": "Contract Tracking",
    "about.contractDesc": "Monitor contracts with detailed information on awards, dates, and current status.",
    "about.resource": "Resource Pool",
    "about.resourceDesc": "Maintain and manage your resource pool with detailed profiles and availability tracking.",
    "about.collaboration": "Team Collaboration",
    "about.collaborationDesc": "Assign and manage team members for engagements with easy member management.",
    "about.contact": "Contact & Support",
    "about.contactText": "For questions or support regarding the ECA Vendor Hub, please contact our support team:",
    "about.email": "Email:",
    "about.hours": "Hours:",
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Find answers to common questions about the ECA Vendor Hub platform.",
    "faq.stillHave": "Still have questions?",
    "faq.noAnswer": "If you can't find the answer you're looking for, please contact our support team at",
    "manuals.title": "Documentation & Manuals",
    "manuals.subtitle": "Access comprehensive guides and manuals to help you make the most of the ECA Vendor Hub platform.",
    "manuals.filterCategory": "Filter by Category",
    "manuals.needHelp": "Need Additional Help?",
    "manuals.needHelpText": "If you can't find what you're looking for in our documentation, our support team is here to help.",
    "manuals.contactSupport": "Contact Support",
    "manuals.download": "Download",
    "manuals.noManuals": "No manuals found for this category.",
    "dashboard.title": "Main Dashboard",
    "dashboard.breadcrumb": "Pages / Dashboard",
    "dashboard.newEngagement": "New Engagement",
    "dashboard.activeEngagement": "Active Engagement",
    "dashboard.totalEngagement": "Total Engagement",
    "dashboard.totalEmployees": "Total Employees",
    "contracts.title": "Contracts",
    "contracts.breadcrumb": "Pages / Contracts",
    "contracts.search": "Search by contract number or manager...",
    "contracts.sortBy": "Sort By",
    "contracts.filterStatus": "Filter by Status",
    "contracts.filterType": "Filter by Type",
    "contracts.contractsList": "Contracts List",
    "contracts.number": "Contract Number",
    "contracts.amount": "Awarded Amount",
    "contracts.startDate": "Start Date",
    "contracts.endDate": "End Date",
    "contracts.status": "Status",
    "contracts.manager": "Project Manager",
    "contracts.type": "Contract Type",
    "contracts.noContracts": "No contracts found matching your search criteria.",
    "engagements.title": "Engagements",
    "engagements.breadcrumb": "Pages / Engagements",
    "engagements.search": "Search by title or requested by...",
    "engagements.sortBy": "Sort By",
    "engagements.filterStatus": "Filter by Status",
    "engagements.engagementsList": "Engagements List",
    "engagements.titleCol": "Engagement Title",
    "engagements.requestedBy": "Requested By",
    "engagements.startDate": "Start Date",
    "engagements.endDate": "End Date",
    "engagements.actions": "Actions",
    "engagements.noEngagements": "No engagements found matching your search criteria.",
    "resources.title": "Resources Pool",
    "resources.breadcrumb": "Pages / Resources Pool",
    "resources.addNew": "Add New Resource",
    "resources.search": "Search using by Name",
    "resources.sortBy": "Sort by Name",
    "resources.filter": "Filter",
    "resources.noPrevious": "← Previous",
    "resources.next": "Next →",
    "profile.title": "Profile",
    "profile.breadcrumb": "Pages / Profile",
    "profile.updateProfile": "Update Your Profile",
    "profile.firstName": "First Name",
    "profile.lastName": "Last Name",
    "profile.email": "Email Address",
    "profile.mobile": "Mobile Number",
    "profile.contactPref": "Preferred Contact Method",
    "profile.save": "Save Changes",
    "profile.cancel": "Cancel",
    "profile.accountInfo": "Account Information",
    "profile.accountStatus": "Account Status",
    "profile.memberSince": "Member Since",
    "profile.lastUpdated": "Last Updated",
    "profile.userRole": "User Role",
    "notfound.title": "Page Not Found",
    "notfound.subtitle": "The page you're looking for doesn't exist or has been moved.",
    "notfound.returnHome": "Return to Home",
    "placeholder.coming": "This page is coming soon. Continue prompting to fill in this page content if you'd like!",
  },
  ar: {
    "nav.about": "حول",
    "nav.faq": "الأسئلة الشائعة",
    "nav.manuals": "الأدلة",
    "nav.login": "دخول",
    "nav.language": "English",
    "index.welcome": "أهلا و سهلا في",
    "index.vendorHub": "مركز الموردين - الهيئة",
    "index.subtitle": "يرجى تسجيل الدخول للوصول إلى الطلبات",
    "index.email": "عنوان البريد الإلكتروني",
    "index.password": "كلمة المرور",
    "index.loginBtn": "دخول",
    "index.register": "سجل الآن",
    "index.registerText": "ليس لديك حساب؟",
    "footer.copyright": "حقوق النشر © {year} الهيئة. جميع الحقوق محفوظة.",
    "footer.terms": "شروط الاستخدام",
    "footer.privacy": "سياسة الخصوصية",
    "about.title": "حول مركز الموردين - الهيئة",
    "about.mission": "مهمتنا",
    "about.missionText": "مركز الموردين - الهيئة هو بوابة شاملة مصممة لتبسيط تفاعل الموردين مع أنشطة الهيئة. مهمتنا هي توفير منصة مركزية سهلة الاستخدام حيث يمكن للموردين الوصول بكفاءة إلى الطلبات وإدارة العقود والتعاون في المشاريع مع الهيئة.",
    "about.whatWeDo": "ما الذي نفعله",
    "about.whatWeDoText": "يعمل مركز الموردين - الهيئة كبوابة عامة رسمية لتفاعل الموردين مع أنشطة الهيئة. من خلال هذه المنصة، يمكن للموردين:",
    "about.features": "المميزات الرئيسية",
    "about.engagement": "إدارة الطلبات",
    "about.engagementDesc": "تتبع وإدارة جميع طلباتك النشطة مع التحديثات في الوقت الفعلي ومراقبة الحالة.",
    "about.contract": "تتبع العقود",
    "about.contractDesc": "مراقبة العقود مع معلومات تفصيلية عن الجوائز والتواريخ والحالة الحالية.",
    "about.resource": "مجموعة الموارد",
    "about.resourceDesc": "الحفاظ على إدارة مجموعة الموارد الخاصة بك مع ملفات تعريف تفصيلية وتتبع التوفر.",
    "about.collaboration": "التعاون الجماعي",
    "about.collaborationDesc": "تعيين وإدارة أعضاء الفريق للطلبات مع إدارة الأعضاء بسهولة.",
    "about.contact": "التواصل والدعم",
    "about.contactText": "للأسئلة أو الدعم فيما يتعلق بمركز الموردين - الهيئة، يرجى التواصل مع فريق الدعم الخاص بنا:",
    "about.email": "البريد الإلكتروني:",
    "about.hours": "الساعات:",
    "faq.title": "الأسئلة الشائعة",
    "faq.subtitle": "ابحث عن إجابات للأسئلة الشائعة حول منصة مركز الموردين - الهيئة.",
    "faq.stillHave": "هل لديك أسئلة أخرى؟",
    "faq.noAnswer": "إذا كنت لا تجد الإجابة التي تبحث عنها، يرجى التواصل مع فريق الدعم الخاص بنا على",
    "manuals.title": "التوثيق والأدلة",
    "manuals.subtitle": "استعرض الأدلة الشاملة والأدلة لمساعدتك في الاستفادة القصوى من منصة مركز الموردين - الهيئة.",
    "manuals.filterCategory": "تصفية حسب الفئة",
    "manuals.needHelp": "هل تحتاج إلى مساعدة إضافية؟",
    "manuals.needHelpText": "إذا كنت لا تجد ما تبحث عنه في التوثيق الخاص بنا، فإن فريق الدعم الخاص بنا موجود لمساعدتك.",
    "manuals.contactSupport": "التواصل مع الدعم",
    "manuals.download": "تحميل",
    "manuals.noManuals": "لم يتم العثور على أدلة لهذه الفئة.",
    "dashboard.title": "لوحة المعلومات الرئيسية",
    "dashboard.breadcrumb": "الصفحات / لوحة المعلومات",
    "dashboard.newEngagement": "طلب جديد",
    "dashboard.activeEngagement": "طلب نشط",
    "dashboard.totalEngagement": "إجمالي الطلبات",
    "dashboard.totalEmployees": "إجمالي الموظفين",
    "contracts.title": "العقود",
    "contracts.breadcrumb": "الصفحات / العقود",
    "contracts.search": "البحث برقم العقد أو اسم المدير...",
    "contracts.sortBy": "ترتيب حسب",
    "contracts.filterStatus": "تصفية حسب الحالة",
    "contracts.filterType": "تصفية حسب النوع",
    "contracts.contractsList": "قائمة العقود",
    "contracts.number": "رقم العقد",
    "contracts.amount": "المبلغ المفترس",
    "contracts.startDate": "تاريخ البدء",
    "contracts.endDate": "تاريخ الانتهاء",
    "contracts.status": "الحالة",
    "contracts.manager": "مدير المشروع",
    "contracts.type": "نوع العقد",
    "contracts.noContracts": "لم يتم العثور على عقود تطابق معايير البحث الخاصة بك.",
    "engagements.title": "الطلبات",
    "engagements.breadcrumb": "الصفحات / الطلبات",
    "engagements.search": "البحث حسب العنوان أو المطلوب من قبل...",
    "engagements.sortBy": "ترتيب حسب",
    "engagements.filterStatus": "تصفية حسب الحالة",
    "engagements.engagementsList": "قائمة الطلبات",
    "engagements.titleCol": "عنوان الطلب",
    "engagements.requestedBy": "مطلوب من",
    "engagements.startDate": "تاريخ البدء",
    "engagements.endDate": "تاريخ الانتهاء",
    "engagements.actions": "الإجراءات",
    "engagements.noEngagements": "لم يتم العثور على طلبات تطابق معايير البحث الخاصة بك.",
    "resources.title": "مجموعة الموارد",
    "resources.breadcrumb": "الصفحات / مجموعة الموارد",
    "resources.addNew": "إضافة مورد جديد",
    "resources.search": "البحث باستخدام الاسم",
    "resources.sortBy": "الترتيب حسب الاسم",
    "resources.filter": "تصفية",
    "resources.noPrevious": "← السابق",
    "resources.next": "التالي →",
    "profile.title": "الملف الشخصي",
    "profile.breadcrumb": "الصفحات / الملف الشخصي",
    "profile.updateProfile": "حدث ملفك الشخصي",
    "profile.firstName": "الاسم الأول",
    "profile.lastName": "اسم العائلة",
    "profile.email": "عنوان البريد الإلكتروني",
    "profile.mobile": "رقم الهاتف المحمول",
    "profile.contactPref": "طريقة الاتصال المفضلة",
    "profile.save": "حفظ التغييرات",
    "profile.cancel": "إلغاء",
    "profile.accountInfo": "معلومات الحساب",
    "profile.accountStatus": "حالة الحساب",
    "profile.memberSince": "عضو منذ",
    "profile.lastUpdated": "آخر تحديث",
    "profile.userRole": "دور المستخدم",
    "notfound.title": "الصفحة غير موجودة",
    "notfound.subtitle": "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.",
    "notfound.returnHome": "العودة إلى الصفحة الرئيسية",
    "placeholder.coming": "هذه الصفحة قريباً. استمر في الإدخال لملء محتوى هذه الصفحة إذا كنت تريد!",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language") as Language | null;
    return saved || "en";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage: handleSetLanguage,
        t,
        isArabic: language === "ar",
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
